### ISSUE TITLE
Does not work for unnamed buffers

### ISSUE THREAD

**Issue by subnut** [PratikBhusal/vim-grip#2]
Suggeestion - 
Use `:w !grip -` to input current buffer contents as stdin to grip

**Comment by PratikBhusal** [comment]
Personally, I do not see a reason for implementing this niche feature request. Hence, I will be closing it. 

**Rationale:**
By piping out the current buffer as the input to `grip`, you lose out on the asynchronous aspect of needing to call `grip` only once every time you want to see changes for a given file. True, calling `:w !grip -` every time you want to see changes is not much more to write than `:w`, but it is a significant enough for me to consider it as a negative change from the norm. 

I did give working with unnamed buffers a shot, but I still could not provide a valid reason nor a good workflow to using unnamed buffers over creating a new file to storage and start working from there.

With that being said, feel free to create a pull request and I'd be more than wiling to review over it.
